### ISSUE TITLE
Why where questions regarding PR #133 marked as off topic?

### ISSUE THREAD

**Issue by S0AndS0** [hasadna/accessible-graphs#134]
Here's a copy of'em to avoid having to open multiple browser windows/tabs...

------

Few questions;

- what is the experience like for different devices and network speeds?

> I ask because not everyone has high-speed, low-latency, and reliable network connections.

- what is the memory foot-print of adding these additional libraries?

> I ask because not everyone will have devices with lots of random access memory

- how robust is the translation between relative links in Markdown and `a` tags within resulting HTML?

> For example will linking to a parent directory's page via `../` cause issues and does serving from a different server break anything?

- what is presented to clients if JavaScript fails to load, ie. is there any indication to clients that content should have loaded dynamically?

> Generally when I run across sites that use JavaScript in questionable ways they'll, have some type of message and/or loading dialog that is replaced _if_ JavaScript does as it was asked.

------

**Comment by oferb** [comment]
We're currently not focused on providing a great solution in every aspect.
We're focusing on certain aspects, and compromising knowingly on the aspects that you mentioned.

**Comment by S0AndS0** [comment]
The title and question of this Issue still needs to be addressed...

------

@oferb why where questions regarding PR #133 marked as off topic?


------

**Comment by oferb** [comment]
GitHub doesn't have an appropriate tag for this IMO. I would have wanted to mark "Low priority" "Low priority discussion" or something like that.

**Comment by S0AndS0** [comment]
Generally when I run across sites that use JavaScript in _questionable_ ways they'll, have some type of message and/or loading dialog that is replaced if JavaScript does as it was asked.

What is presented to clients if JavaScript fails to load, ie. is there any indication to clients that content should have loaded dynamically?

**Comment by oferb** [comment]
Dealing with a situation where javascript fails to load is out of scope for now.

**Comment by S0AndS0** [comment]
> @oferb
> Dealing with a situation where javascript fails to load is out of scope for now.

Is that an appropriate stance for a project aiming to improve accessibility should take?

**Comment by oferb** [comment]
We're aiming to develop a new method to make graphs accessible.

To get there faster (i.e to increase the probability of project success), we're deprioritizing other aspects, for now. It doesn't mean they will stay like that forever.

BTW, you use accessibility in a very broad term. Disabling javascript has nothing to do really with disability-related accessibility (e.g visual impairment), which is what accessibility usually refers to.

**Comment by S0AndS0** [comment]
> @oferb
> GitHub doesn't have an appropriate tag for this IMO. I would have wanted to mark "Low priority" or something like that.


Why should I believe that?


I ask because closing the feedback as "off topic", without any statement, seems to run counter to the [Contributor Covenant -- Our Standards](https://www.contributor-covenant.org/version/2/0/code_of_conduct/#our-standards). Specifically section; _"Giving and gracefully **accepting** constructive feedback"_


> @oferb
> We're aiming to develop a new method to make graphs accessible.
>
> To get there faster (i.e to increase the probability of project success), we're deprioritizing other aspects, for now. It doesn't mean they will stay like that forever.


How exactly does requiring JavaScript to read **static** content _"increase the probability of project success"_ for clients?


I ask because it seems to me that requiring unnecessary JavaScript only increases the likelihood of failure to provide services to clients, and this as far as I can tell runs counter to _"Focusing on what is best not just for us as individuals, but for the **overall community**"_

**Comment by oferb** [comment]
I accept your constructive feedback.

We're focusing on certain aspects, and deprioritizing others. That means that we may not do a good job in those other, deprioritized aspects. One of those aspects is the experience when javascript is disabled or not working for some other reason.

By focusing on "our core", and prioritizing it, we increase the probability of project success.

Think about it this way - what is this project about? It's about building a great tool to help blind people understand data. This is an ambiguous task, because frankly speaking, it's not clear how to do it well. That's where most of our efforts should go. Our job is not done here.

The task of making a website work well for users with javascript disabled is not ambiguous. For example, we could find someone with the required expertise, and ask them to basically rewrite the whole website from scratch using a static site builder. I'm sure it'll solve the problem! In fact, you already did that and got it almost working or even fully working :) So you know that it's not something that can't be done.

We're trying to carve out sections of the problem domain by order of risk - taking the riskier ones first. Why? You can think of 2 primary aspects of the project - utility (for the task at hand) and distribution. Let's give our tool an awesomeness utility grade from 1 to 100. Currently it's at 70. Nobody knows if it can get to 80, because 70 is actually the best that's ever been built. Our primary focus is on getting that number as high up as we can, while still preserving a low-risk path to reach a distribution to 99.9% of people.

What does a high-risk path look like? If, for example, we were to develop new hardware, we could maybe get to utility grade 95 more easily at first, but the path to get to 99.9% of people would be high risk (hardware manufacturing, payments, shipments, warranty, people not willing to actually pay, time to market etc).

So that's the guiding principle for the prioritization. I hope that helps clear it up.

**Comment by S0AndS0** [comment]
> @oferb
> I accept your constructive feedback.


That this issue is opened is sufficient evidence to show that the above statement is false. And in your exuberance to answer your own questions you've missed at least one that I've asked.


To mitigate your future distraction, and so that you don't need to scroll excessively here it is again...


> @oferb
> GitHub doesn't have an appropriate tag for this IMO. I would have wanted to mark "Low priority" or something like that.


Why should I believe that?

**Comment by oferb** [comment]
Sorry, I don't follow. Why should you believe me? I don't know.
You decide if you want to believe it, or not.

**Comment by S0AndS0** [comment]
If you are unable to follow, then it would likely be a good idea to review the whole conversation. Because until you can come up with a honest reason as to why I should believe the following statement...

> @oferb
> GitHub doesn't have an appropriate tag for this IMO. I would have wanted to mark "Low priority" or something like that.

... I will have to put working with you on a time-out.

**Comment by oferb** [comment]
If you don't want to believe my explanation for something I did, you can choose to do so.

Not sure what you want me to say, or do, at this point. If you want to take a time-out, that's of course fine. Of course we always appreciate help, but in this case I'd say - do what's best for you. In any case, thank you again for your help with the project.

**Comment by S0AndS0** [comment]
Feel free to let me know if you're able to come up with a legit reason as to why I should believe you in the future. Because while was willing to I put-up with your temper tantrums on Twitter, I'll not work with someone overtly dishonest.

**Comment by oferb** [comment]
If you don't want to focus on the priorities of the project, and are taking time away from people working on those priorities, and on top of that, are telling me that I am dishonest, have temper tantrums, and other things, then it begs the question, what is your motivation? Do you just want to argue? Are you trying to prove some point on the internet?

If you want to help with the project, you need to be aligned with the priorities of people already working on the project. To work with us, you need to accept our opinions, which differ from yours sometimes. Also, discussing those priorities, the reasoning behind them etc, can be done to a certain extent, but at some level of detail, is also time-consuming.

There _is_ a gap of knowledge about the project, understanding of the problem domain, opinions, etc, that can't be overcome easily, and so, some decisions should be accepted _as is_.
Imagine you go volunteer for a few hours a week in the Large Hadron Collider and you tell them that they should reprioritize something there, and then when they disagree, you start going and trying to insistently convince them, telling the manager that he's forcing his employees to do something that's bad for them etc.

At the end of the day, it seems there is a trust issue. Not only in that statement I made, but also, in that the priorities for the project are incorrect. As said, some trust needs to be given in a project, because you should take into account that you don't understand everything like other people on the project, don't have their experiences, viewpoints, skills.

Lastly, you seem to be very keen about privacy. This project is about accessibility. As you can see, we've chosen to prioritize accessibility over privacy-by-design, but, given better design options, we would have not had to compromise.

Maybe you want to work and develop solutions to these problems, so that they could help other projects, as well as ours? For example, something that somehow strips certain url params before it sends them to a server. Or maybe a secure proxy that does that. Maybe some sort of encryption? I don't know what the solution may be, but I'm proposing a problem for you to work on, that's orthogonal to the project, but, could help it down the line improve its privacy-by-design.

**Comment by S0AndS0** [comment]
Feel free to let me know if you're able to come up with a legit reason as to why I should believe you in the future.
