### ISSUE TITLE
Tell user if browser/OS combination is unsupported

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#88]

**Comment by S0AndS0** [comment]
Browsers are moving away from allowing scripts to finger-print environments, here's one example that shows one cannot reliably get the Browser's name...


```JavaScript
// Firefox
navigator.appName
//> "Netscape"

// Chrome
navigator.appName
//> "Netscape"
```

... instead I'd suggest feature detection...


```JavaScript
if (!('feature' in document)) {
  // Workaround or throw error
  console.error(new Error('`feature` not available on document'));
  document.feature = function() {
    console.log('arguments ->', ...arguments);
  };
}
document.feature('stuff');


// or...


try {
  document.feature('stuff');
} catch (e) {
  if (e instanceof TypeError) {
    console.error(e);
    // Workaround or re-throw error
    document.feature = function() {
      console.log('arguments ->', ...arguments);
    };

    document.feature('stuff');
  }
}
```


... not only for previously mentioned reasons, but also because Browsers may implement target feature(s) in the future.


Feature detection means future-proofing where as finger-printing means future maintenance, and eventual failure when all browsers standardize their fictitious reporting about client environment.

**Comment by oferb** [comment]
Right, but, unfortunately we don't have a feature to check.

**Comment by S0AndS0** [comment]
If there is no feature to test then adding a notice somewhere that specific Browsers are better supported than others is the only thing that I'm aware of that'll work, because vendors are actively removing ways for scripts to finger-print environments.

**Comment by oferb** [comment]
> the only thing that I'm aware of that'll work
You mean that will work _always_? Because on my browser it does detect my OS and browser.

**Comment by S0AndS0** [comment]
Vendors are actively removing ways for scripts to finger-print environments, so the only thing that I'm aware of that'll work across all platforms is notifying clients that some Browser and Operating System combinations are better supported than others. Eg. a list would need to be compiled within the GitHub branch of site files so that contributors can keep it updated.

**Comment by oferb** [comment]
> work across all platforms
We don't need 100% accuracy.
So if sometimes it won't work, it's fine.
It's still good if it's, say 97%.

Also, removing finger-printing doesn't mean they're removing these basic attributes. Finger-printing (identifying a particular machine) needs more than just browser and OS version.

Do you think we can't get to 97% accuracy?

**Comment by S0AndS0** [comment]
While I think it may be possible, I also think that doing so is not a sustainable strategy, because vendors are actively removing ways for scripts to finger-print environments.

Feature detection via `try`/`catch` statements, and/or notifying clients that specific OS/Browser combinations are best supported, is by far more maintainable.

**Comment by oferb** [comment]
Referring to this:
"While I think it may be possible, though only for a short period of time, I also think that doing so is not a sustainable long-term strategy, because vendors are actively removing ways for scripts to finger-print environments."

What do you base this off of? Do you have some source that states that browsers are removing browser version and OS?

**Comment by S0AndS0** [comment]
You can find evidence via searching online or by testing it yourself...


**WebKit -- Chrome**

```javascript
window.navigator.appCodeName
//> "Mozilla"
```


**Gecko -- Firefox**

```javascript
window.navigator.appCodeName
//> "Mozilla"
```


... feature detection instead of device finger-printing is far more sustainable, not only because vendors are actively removing the ability to differentiate between browsers, but also because vendors could update their APIs.

**Comment by oferb** [comment]
"The NavigatorID.appCodeName always returns 'Mozilla', on any browser. This property is kept only for compatibility purposes."
https://stackoverflow.com/a/30850666/374047

**Comment by S0AndS0** [comment]
This is but one example of how vendors are _encouraging_ developers to not use fingerprinting, and this trend will continue. Furthermore it is not possible, or recommended, to trust browsers to self identify; settings as well as extensions are able to spoof such information.

Feature detection instead of device finger-printing is more sustainable, because vendors could update their APIs.

**Comment by oferb** [comment]
Please see issue #195
